AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 28

Naming/PredicateMethod:
  AllowedMethods:
    - validate!

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Lint/InterpolationCheck:
  Exclude:
    - "lib/generators/**/*"
